// SPDX-License-Identifier: Apache-2.0
// Generated by app/build/export_data.py from model/build/spec_data.py. Do not edit by hand.
(function (root) {
  var DATA = {
   "meta": {
    "priceDate": "2026-09-20",
    "version": "0.2 preview",
    "horizonMax": 60,
    "org": {
     "name": "Northwind Example Co (fictional)",
     "horizon": 36,
     "scenario": "Base",
     "value_case": "Base",
     "shape": "Hub-and-spoke",
     "alloc": "Usage-proportional",
     "pd_rate": 800,
     "hours_day": 8,
     "work_days": 220,
     "obs_per_out": 5
    }
   },
   "orgFields": {
    "name": {
     "label": "Organization name",
     "unit": "text",
     "source": "Fictional worked example (Claude, 2026-09-20)",
     "grade": "D"
    },
    "horizon": {
     "label": "Horizon",
     "unit": "months (max 60)",
     "source": "Project owner's choice, 2026-09-20",
     "grade": "D"
    },
    "scenario": {
     "label": "Scenario shown on Summary",
     "unit": "Low-cost / Base / High-cost (High-cost is a stress case: every parameter at its high value at once)",
     "source": "User choice",
     "grade": "D"
    },
    "value_case": {
     "label": "Value case (realisation share)",
     "unit": "Low / Base / High",
     "source": "User choice",
     "grade": "D"
    },
    "shape": {
     "label": "Org shape",
     "unit": "Centralized / Federated / Hub-and-spoke",
     "source": "User choice; definitions in research/enterprise-structure.md",
     "grade": "D"
    },
    "alloc": {
     "label": "Allocation rule",
     "unit": "Usage-proportional / Headcount proxy / Even split / Central budget",
     "source": "Default per shape (D), research/enterprise-structure.md",
     "grade": "D"
    },
    "pd_rate": {
     "label": "Person-day rate",
     "unit": "USD per person-day",
     "source": "spec/starter-values.md (Claude, 2026-09-20); cross-check BLS LAB-02 (S41, S42)",
     "grade": "D"
    },
    "hours_day": {
     "label": "Hours per person-day",
     "unit": "hours",
     "source": "spec/starter-values.md (Claude, 2026-09-20)",
     "grade": "D"
    },
    "work_days": {
     "label": "Working days per year",
     "unit": "days",
     "source": "spec/starter-values.md (Claude, 2026-09-20)",
     "grade": "D"
    },
    "obs_per_out": {
     "label": "Monitoring units per outcome",
     "unit": "units",
     "source": "Fictional worked example (Claude, 2026-09-20)",
     "grade": "D"
    }
   },
   "params": {
    "src_pd": {
     "desc": "Assess one source system",
     "unit": "person-days",
     "vals": [
      1,
      3,
      8
     ],
     "line": "CL-01",
     "why": "Owner interview, access check, sample review",
     "grade": "D"
    },
    "clean_pd": {
     "desc": "Clean and label 100,000 documents",
     "unit": "person-days",
     "vals": [
      5,
      20,
      60
     ],
     "line": "CL-02",
     "why": "Pipeline plus sampled review; range wide because published shares conflict (CST-07)",
     "grade": "D"
    },
    "conn_pd": {
     "desc": "Build one connector",
     "unit": "person-days",
     "vals": [
      5,
      10,
      25
     ],
     "line": "CL-03",
     "why": "Standard vs custom source",
     "grade": "D"
    },
    "conn_up": {
     "desc": "Connector upkeep per year",
     "unit": "share of build",
     "vals": [
      0.1,
      0.15,
      0.25
     ],
     "line": "CL-03",
     "why": "Yearly upkeep share",
     "grade": "D"
    },
    "perm_pd": {
     "desc": "Map permissions for one source",
     "unit": "person-days",
     "vals": [
      2,
      4,
      10
     ],
     "line": "CL-04",
     "why": "Map groups once, revise on org change",
     "grade": "D"
    },
    "perm_up": {
     "desc": "Permission upkeep per year",
     "unit": "share of build",
     "vals": [
      0.05,
      0.1,
      0.2
     ],
     "line": "CL-04",
     "why": "Org change rate",
     "grade": "D"
    },
    "change_rate": {
     "desc": "Share of documents changing per month",
     "unit": "share",
     "vals": [
      0.01,
      0.03,
      0.1
     ],
     "line": "CL-08",
     "why": "Slow policy content vs fast tickets",
     "grade": "D"
    },
    "plat_pd": {
     "desc": "Platform or gateway, one-time",
     "unit": "person-days",
     "vals": [
      60,
      120,
      300
     ],
     "line": "CL-09",
     "why": "Configure or build gateway with logging and access control; base x rate = $96,000 vs ENV-01 (B*, 2024)",
     "grade": "D"
    },
    "plat_run": {
     "desc": "Platform run per year",
     "unit": "share of one-time",
     "vals": [
      0.1,
      0.2,
      0.3
     ],
     "line": "CL-09",
     "why": "Yearly run share",
     "grade": "D"
    },
    "int_pd": {
     "desc": "Integrate one use case",
     "unit": "person-days",
     "vals": [
      15,
      40,
      120
     ],
     "line": "CL-10",
     "why": "Connect one workflow and its systems",
     "grade": "D"
    },
    "rev_uc_pd": {
     "desc": "Security, privacy, legal review per use case",
     "unit": "person-days",
     "vals": [
      5,
      10,
      30
     ],
     "line": "CL-11",
     "why": "A few days each from three reviewers",
     "grade": "D"
    },
    "rev_once_pd": {
     "desc": "Platform-level review, once",
     "unit": "person-days",
     "vals": [
      15,
      30,
      60
     ],
     "line": "CL-11",
     "why": "One-time platform review",
     "grade": "D"
    },
    "eval_pd": {
     "desc": "Evaluation harness per use case",
     "unit": "person-days",
     "vals": [
      8,
      20,
      60
     ],
     "line": "CL-12",
     "why": "Build a test set and scoring",
     "grade": "D"
    },
    "eval_rerun": {
     "desc": "Share of harness re-done per model change",
     "unit": "share",
     "vals": [
      0.15,
      0.25,
      0.4
     ],
     "line": "CL-12",
     "why": "Re-run when the model changes",
     "grade": "D"
    },
    "rt_pd": {
     "desc": "Red-team one use case",
     "unit": "person-days",
     "vals": [
      3,
      8,
      25
     ],
     "line": "CL-13",
     "why": "Adversarial testing before launch",
     "grade": "D"
    },
    "rt_rep": {
     "desc": "Red-team repeat per year",
     "unit": "share of one-time",
     "vals": [
      0.25,
      0.5,
      1.0
     ],
     "line": "CL-13",
     "why": "Periodic repeat",
     "grade": "D"
    },
    "env_month": {
     "desc": "Environments and base infrastructure",
     "unit": "USD per month",
     "vals": [
      0,
      0,
      0
     ],
     "line": "CL-14",
     "why": "No starter: off until entered (approved 2026-09-20)",
     "grade": "D"
    },
    "retry": {
     "desc": "Retry and failure multiplier on tokens",
     "unit": "multiplier",
     "vals": [
      1.05,
      1.15,
      1.5
     ],
     "line": "CL-17",
     "why": "Minority of calls retried (G8)",
     "grade": "D"
    },
    "steps": {
     "desc": "Agent steps per outcome (agentic teams)",
     "unit": "count",
     "vals": [
      3,
      6,
      20
     ],
     "line": "CL-17",
     "why": "Plan, tool calls, check (G8)",
     "grade": "D"
    },
    "evalcases": {
     "desc": "Quality-review cases per month per use case",
     "unit": "cases",
     "vals": [
      50,
      200,
      1000
     ],
     "line": "CL-25",
     "why": "Sample outputs and score them",
     "grade": "D"
    },
    "eval_min": {
     "desc": "Minutes per quality-review case",
     "unit": "minutes",
     "vals": [
      5,
      10,
      20
     ],
     "line": "CL-25",
     "why": "Read and score one output",
     "grade": "D"
    },
    "mig_int": {
     "desc": "Months between model migration events",
     "unit": "months",
     "vals": [
      25,
      15,
      12
     ],
     "line": "CL-26",
     "why": "Derived from retirement data: min 12, median 14.5, max 25.4 (PRC-06, one provider)",
     "grade": "C"
    },
    "mig_pd": {
     "desc": "Re-evaluate one workflow per migration event",
     "unit": "person-days",
     "vals": [
      1,
      3,
      10
     ],
     "line": "CL-26",
     "why": "Effort per workflow (G12)",
     "grade": "D"
    },
    "maint": {
     "desc": "Workflow maintenance per year",
     "unit": "share of integration",
     "vals": [
      0.05,
      0.1,
      0.25
     ],
     "line": "CL-27",
     "why": "Prompt changes and fixes",
     "grade": "D"
    },
    "tickets": {
     "desc": "Support tickets per 1,000 active users per month",
     "unit": "tickets",
     "vals": [
      5,
      20,
      60
     ],
     "line": "CL-28",
     "why": "Questions and incidents",
     "grade": "D"
    },
    "tkt_hours": {
     "desc": "Hours per support ticket",
     "unit": "hours",
     "vals": [
      0.5,
      1,
      2
     ],
     "line": "CL-28",
     "why": "Handle one ticket",
     "grade": "D"
    },
    "plat_fte": {
     "desc": "Hub platform team",
     "unit": "FTE",
     "vals": [
      3,
      5,
      12
     ],
     "line": "CL-29",
     "why": "Product owner, two engineers, data engineer, governance lead",
     "grade": "D"
    },
    "gov_fte": {
     "desc": "AI cost governance",
     "unit": "FTE",
     "vals": [
      0.5,
      1,
      3
     ],
     "line": "CL-30",
     "why": "AI share of a FinOps function; ORG-07 covers the whole function (B)",
     "grade": "C"
    },
    "comp_year": {
     "desc": "Compliance audit and governance",
     "unit": "USD per year",
     "vals": [
      0,
      0,
      0
     ],
     "line": "CL-31",
     "why": "No starter: off until entered (approved 2026-09-20)",
     "grade": "D"
    },
    "lic_year": {
     "desc": "Platform and vendor licences",
     "unit": "USD per year",
     "vals": [
      0,
      0,
      0
     ],
     "line": "CL-32",
     "why": "No starter: enter quotes",
     "grade": "D"
    },
    "train_hours": {
     "desc": "Training per active user, one-time",
     "unit": "hours",
     "vals": [
      2,
      4,
      12
     ],
     "line": "CL-33",
     "why": "Short course plus practice",
     "grade": "D"
    },
    "rev_mult": {
     "desc": "Human review share multiplier",
     "unit": "multiplier (capped at 100%)",
     "vals": [
      0.5,
      1,
      2
     ],
     "line": "CL-34",
     "why": "Low is base x 0.5; high is base x 2",
     "grade": "C"
    },
    "rev_min": {
     "desc": "Minutes per human review",
     "unit": "minutes",
     "vals": [
      2,
      3,
      6
     ],
     "line": "CL-34",
     "why": "Review one output; ORG-06 review shares (B*). Range narrowed from 1/3/10 at Phase 5 approval",
     "grade": "C"
    },
    "cm_ramp": {
     "desc": "Change champions during first 6 months",
     "unit": "FTE per 1,000 licensed",
     "vals": [
      0.25,
      0.5,
      1.0
     ],
     "line": "CL-35",
     "why": "Champions and communications during ramp",
     "grade": "D"
    },
    "cm_after": {
     "desc": "Change champions after ramp",
     "unit": "FTE per 1,000 licensed",
     "vals": [
      0.05,
      0.1,
      0.2
     ],
     "line": "CL-35",
     "why": "Sustaining communications",
     "grade": "D"
    },
    "tok_mult": {
     "desc": "Tokens-per-outcome scenario multiplier",
     "unit": "multiplier",
     "vals": [
      0.7,
      1.0,
      1.5
     ],
     "line": "CL-16",
     "why": "Wide band by design (FCS-01, C)",
     "grade": "D"
    },
    "fed_dup": {
     "desc": "Federated: each unit's platform as share of a full hub platform",
     "unit": "share",
     "vals": [
      0.3,
      0.5,
      0.7
     ],
     "line": "org shape",
     "why": "No evidence on duplication (G4)",
     "grade": "D"
    },
    "realise": {
     "desc": "Realisation share of self-reported time saved",
     "unit": "share",
     "vals": [
      0.25,
      0.5,
      0.75
     ],
     "line": "value",
     "why": "No evidence converts self-reported time saved to cash (G5)",
     "grade": "D"
    }
   },
   "pricebook": [
    {
     "id": "M_HAIKU45",
     "provider": "Anthropic",
     "product": "Claude Haiku 4.5",
     "kind": "Model",
     "p_in": 1.0,
     "p_out": 5.0,
     "c_read": 0.1,
     "c_write": 1.25,
     "batch": 0.5,
     "unit": "USD per million tokens",
     "src": "S09",
     "status": "standard",
     "to": null
    },
    {
     "id": "M_SONNET5",
     "provider": "Anthropic",
     "product": "Claude Sonnet 5",
     "kind": "Model",
     "p_in": 2.0,
     "p_out": 10.0,
     "c_read": 0.1,
     "c_write": 1.25,
     "batch": 0.5,
     "unit": "USD per million tokens",
     "src": "S09",
     "status": "standard",
     "to": null
    },
    {
     "id": "M_OPUS5",
     "provider": "Anthropic",
     "product": "Claude Opus 5",
     "kind": "Model",
     "p_in": 5.0,
     "p_out": 25.0,
     "c_read": 0.1,
     "c_write": 1.25,
     "batch": 0.5,
     "unit": "USD per million tokens",
     "src": "S09",
     "status": "standard",
     "to": null
    },
    {
     "id": "M_GPT54MINI",
     "provider": "OpenAI",
     "product": "GPT-5.4 Mini (name as extracted)",
     "kind": "Model",
     "p_in": 0.75,
     "p_out": 4.5,
     "c_read": 0.1,
     "c_write": 1.0,
     "batch": 0.5,
     "unit": "USD per million tokens",
     "src": "S12",
     "status": "standard",
     "to": null
    },
    {
     "id": "M_GEM38FLASH",
     "provider": "Google",
     "product": "Gemini 3.8 Flash (name as extracted)",
     "kind": "Model",
     "p_in": 0.75,
     "p_out": 3.75,
     "c_read": 0.1,
     "c_write": 1.0,
     "batch": 0.5,
     "unit": "USD per million tokens",
     "src": "S11",
     "status": "promotional",
     "to": "2026-12-31"
    },
    {
     "id": "SEAT_TEAM_STD",
     "provider": "Anthropic",
     "product": "Claude Team standard seat (annual billing)",
     "kind": "Seat",
     "p_in": 20.0,
     "unit": "USD per user per month",
     "src": "S33",
     "status": "standard",
     "to": null
    },
    {
     "id": "SEAT_TEAM_PREM",
     "provider": "Anthropic",
     "product": "Claude Team premium seat (annual billing)",
     "kind": "Seat",
     "p_in": 100.0,
     "unit": "USD per user per month",
     "src": "S33",
     "status": "standard",
     "to": null
    },
    {
     "id": "SEAT_ENT",
     "provider": "Anthropic",
     "product": "Claude Enterprise seat (annual); usage billed at API rates",
     "kind": "Seat",
     "p_in": 20.0,
     "unit": "USD per user per month",
     "src": "S33",
     "status": "standard",
     "to": null
    },
    {
     "id": "SEAT_M365_BUS",
     "provider": "Microsoft",
     "product": "Microsoft 365 Copilot Business (annual, promotional)",
     "kind": "Seat",
     "p_in": 18.0,
     "unit": "USD per user per month",
     "src": "S08",
     "status": "promotional",
     "to": "2026-12-31"
    },
    {
     "id": "SEAT_M365",
     "provider": "Microsoft",
     "product": "Microsoft 365 Copilot (paid yearly)",
     "kind": "Seat",
     "p_in": 30.0,
     "unit": "USD per user per month",
     "src": "S35",
     "status": "standard",
     "to": null
    },
    {
     "id": "OUT_FIN",
     "provider": "Intercom",
     "product": "Fin AI agent, per outcome (outcome definition in BUY-06)",
     "kind": "Outcome",
     "p_in": 0.99,
     "unit": "USD per outcome",
     "src": "S37",
     "status": "standard",
     "to": null
    },
    {
     "id": "U_TEXTRACT_TXT",
     "provider": "AWS",
     "product": "Textract detect text, first 1M pages",
     "kind": "Unit",
     "p_in": 0.0015,
     "unit": "USD per page",
     "src": "S45",
     "status": "standard",
     "to": null
    },
    {
     "id": "U_TEXTRACT_TBL",
     "provider": "AWS",
     "product": "Textract tables, first 1M pages",
     "kind": "Unit",
     "p_in": 0.015,
     "unit": "USD per page",
     "src": "S45",
     "status": "standard",
     "to": null
    },
    {
     "id": "U_EMB_3L",
     "provider": "OpenAI",
     "product": "text-embedding-3-large",
     "kind": "Unit",
     "p_in": 0.13,
     "unit": "USD per million tokens",
     "src": "S12",
     "status": "standard",
     "to": null
    },
    {
     "id": "U_PINE_READ",
     "provider": "Pinecone",
     "product": "Read units (low end of range)",
     "kind": "Unit",
     "p_in": 16.0,
     "unit": "USD per million read units",
     "src": "S43",
     "status": "standard",
     "to": null
    },
    {
     "id": "U_PINE_STORE",
     "provider": "Pinecone",
     "product": "Storage, Standard plan",
     "kind": "Unit",
     "p_in": 0.33,
     "unit": "USD per GB per month",
     "src": "S43",
     "status": "standard",
     "to": null
    },
    {
     "id": "PL_PINE_STD",
     "provider": "Pinecone",
     "product": "Standard plan minimum",
     "kind": "Plan",
     "p_in": 50.0,
     "unit": "USD per month",
     "src": "S43",
     "status": "standard",
     "to": null
    },
    {
     "id": "U_GUARD_CF",
     "provider": "AWS",
     "product": "Bedrock Guardrails content filters",
     "kind": "Unit",
     "p_in": 0.15,
     "unit": "USD per 1,000 text units",
     "src": "S46",
     "status": "standard",
     "to": null
    },
    {
     "id": "U_TOOL_SEARCH",
     "provider": "Anthropic/OpenAI",
     "product": "Web search tool",
     "kind": "Unit",
     "p_in": 10.0,
     "unit": "USD per 1,000 calls",
     "src": "S09",
     "status": "standard",
     "to": null
    },
    {
     "id": "PL_LANGFUSE_PRO",
     "provider": "Langfuse",
     "product": "Pro plan (100k units included)",
     "kind": "Plan",
     "p_in": 199.0,
     "unit": "USD per month",
     "src": "S44",
     "status": "standard",
     "to": null
    },
    {
     "id": "U_LANGFUSE_OVER",
     "provider": "Langfuse",
     "product": "Overage per 100k units",
     "kind": "Unit",
     "p_in": 8.0,
     "unit": "USD per 100k units",
     "src": "S44",
     "status": "standard",
     "to": null
    }
   ],
   "priceLabels": {
    "M_HAIKU45": "Anthropic Claude Haiku 4.5",
    "M_SONNET5": "Anthropic Claude Sonnet 5",
    "M_OPUS5": "Anthropic Claude Opus 5",
    "M_GPT54MINI": "OpenAI GPT-5.4 Mini (name as extracted)",
    "M_GEM38FLASH": "Google Gemini 3.8 Flash (name as extracted) (promotional until 2026-12-31)",
    "SEAT_TEAM_STD": "Anthropic Claude Team standard seat (annual billing)",
    "SEAT_TEAM_PREM": "Anthropic Claude Team premium seat (annual billing)",
    "SEAT_ENT": "Anthropic Claude Enterprise seat (annual); usage billed at API rates",
    "SEAT_M365_BUS": "Microsoft Microsoft 365 Copilot Business (annual, promotional) (promotional until 2026-12-31)",
    "SEAT_M365": "Microsoft Microsoft 365 Copilot (paid yearly)",
    "OUT_FIN": "Intercom Fin AI agent, per outcome (outcome definition in BUY-06)",
    "U_TEXTRACT_TXT": "AWS Textract detect text, first 1M pages",
    "U_TEXTRACT_TBL": "AWS Textract tables, first 1M pages",
    "U_EMB_3L": "OpenAI text-embedding-3-large",
    "U_PINE_READ": "Pinecone Read units (low end of range)",
    "U_PINE_STORE": "Pinecone Storage, Standard plan",
    "PL_PINE_STD": "Pinecone Standard plan minimum",
    "U_GUARD_CF": "AWS Bedrock Guardrails content filters",
    "U_TOOL_SEARCH": "Anthropic/OpenAI Web search tool",
    "PL_LANGFUSE_PRO": "Langfuse Pro plan (100k units included)",
    "U_LANGFUSE_OVER": "Langfuse Overage per 100k units"
   },
   "fields": {
    "name": {
     "label": "Team name",
     "unit": "text",
     "kind": "text"
    },
    "active": {
     "label": "Team is active (1 = counted, 0 = ignored)",
     "unit": "1 / 0",
     "kind": "number"
    },
    "archetype": {
     "label": "Archetype",
     "unit": "text",
     "kind": "text"
    },
    "bu": {
     "label": "Business unit and cost center",
     "unit": "text",
     "kind": "text"
    },
    "buy": {
     "label": "Buying model",
     "unit": "Seat / Seat + usage / Per-unit / Committed capacity",
     "kind": "select",
     "options": [
      "Seat",
      "Seat + usage",
      "Per-unit",
      "Committed capacity"
     ]
    },
    "seat_std": {
     "label": "Seat price (price book ID)",
     "unit": "ID",
     "kind": "price",
     "priceKind": "Seat",
     "allowNone": false
    },
    "seat_prem": {
     "label": "Premium seat price (price book ID)",
     "unit": "ID",
     "kind": "price",
     "priceKind": "Seat",
     "allowNone": false
    },
    "prem_share": {
     "label": "Share of licensed users on premium seats",
     "unit": "share",
     "kind": "percent"
    },
    "allow": {
     "label": "Usage included per seat per month (hybrid)",
     "unit": "USD",
     "kind": "number"
    },
    "top_share": {
     "label": "Top segment share of active users",
     "unit": "share",
     "kind": "percent"
    },
    "top_mult": {
     "label": "Top segment intensity vs the rest",
     "unit": "multiple",
     "kind": "number"
    },
    "unit_price": {
     "label": "Vendor per-outcome price (price book ID, or none)",
     "unit": "ID",
     "kind": "price",
     "priceKind": "Outcome",
     "allowNone": true
    },
    "cap_cost": {
     "label": "Committed capacity cost",
     "unit": "USD per month",
     "kind": "number"
    },
    "licensed": {
     "label": "Licensed users",
     "unit": "users",
     "kind": "number"
    },
    "plateau": {
     "label": "Active share of licensed users at plateau",
     "unit": "share",
     "kind": "percent"
    },
    "start": {
     "label": "Launch month",
     "unit": "month",
     "kind": "number"
    },
    "ramp": {
     "label": "Months to plateau",
     "unit": "months",
     "kind": "number"
    },
    "curve": {
     "label": "Ramp curve",
     "unit": "Linear / S",
     "kind": "select",
     "options": [
      "Linear",
      "S"
     ]
    },
    "basis": {
     "label": "Outcome basis",
     "unit": "per user / direct volume",
     "kind": "select",
     "options": [
      "per user",
      "direct volume"
     ]
    },
    "o_user": {
     "label": "Outcomes per active user per month",
     "unit": "outcomes",
     "kind": "number"
    },
    "direct": {
     "label": "Direct volume at plateau",
     "unit": "outcomes per month",
     "kind": "number"
    },
    "model": {
     "label": "Main model (price book ID)",
     "unit": "ID",
     "kind": "price",
     "priceKind": "Model",
     "allowNone": false
    },
    "cheap": {
     "label": "Cheaper model (price book ID)",
     "unit": "ID",
     "kind": "price",
     "priceKind": "Model",
     "allowNone": false
    },
    "route": {
     "label": "Share routed to cheaper model",
     "unit": "share",
     "kind": "percent"
    },
    "tok_in": {
     "label": "Input tokens per outcome",
     "unit": "tokens",
     "kind": "number"
    },
    "tok_out": {
     "label": "Output tokens per outcome",
     "unit": "tokens",
     "kind": "number"
    },
    "ctx": {
     "label": "Context-management reduction",
     "unit": "share",
     "kind": "percent"
    },
    "cached": {
     "label": "Cached share of input",
     "unit": "share",
     "kind": "percent"
    },
    "cwrite": {
     "label": "Cache-write share of input",
     "unit": "share",
     "kind": "percent"
    },
    "async_": {
     "label": "Asynchronous (batch) share",
     "unit": "share",
     "kind": "percent"
    },
    "resid": {
     "label": "Residency multiplier",
     "unit": "multiplier",
     "kind": "number"
    },
    "agentic": {
     "label": "Agentic workflow",
     "unit": "Yes / No",
     "kind": "select",
     "options": [
      "No",
      "Yes"
     ]
    },
    "tool_calls": {
     "label": "Tool calls per outcome",
     "unit": "calls",
     "kind": "number"
    },
    "tool_price": {
     "label": "Tool price (price book ID)",
     "unit": "ID",
     "kind": "price",
     "priceKind": "Unit",
     "allowNone": false
    },
    "guard_units": {
     "label": "Guardrail text units per outcome",
     "unit": "units",
     "kind": "number"
    },
    "guard_price": {
     "label": "Guardrail price (price book ID)",
     "unit": "ID",
     "kind": "price",
     "priceKind": "Unit",
     "allowNone": false
    },
    "review": {
     "label": "Human review share of outputs",
     "unit": "share",
     "kind": "percent"
    },
    "rev_rate": {
     "label": "Reviewer loaded rate",
     "unit": "USD per hour",
     "kind": "number"
    },
    "nsrc": {
     "label": "Source systems",
     "unit": "count",
     "kind": "number"
    },
    "ndocs": {
     "label": "Documents",
     "unit": "count",
     "kind": "number"
    },
    "pages": {
     "label": "Pages per document",
     "unit": "pages",
     "kind": "number"
    },
    "parse_price": {
     "label": "Parsing price (price book ID)",
     "unit": "ID",
     "kind": "price",
     "priceKind": "Unit",
     "allowNone": false
    },
    "emb_tok": {
     "label": "Embedding tokens per document",
     "unit": "tokens",
     "kind": "number"
    },
    "emb_price": {
     "label": "Embedding price (price book ID)",
     "unit": "ID",
     "kind": "price",
     "priceKind": "Unit",
     "allowNone": false
    },
    "own_index": {
     "label": "Team runs its own index",
     "unit": "1 / 0",
     "kind": "toggle"
    },
    "gb": {
     "label": "Index storage",
     "unit": "GB",
     "kind": "number"
    },
    "read_units": {
     "label": "Read units per outcome",
     "unit": "units",
     "kind": "number"
    },
    "plan_price": {
     "label": "Index plan minimum (price book ID)",
     "unit": "ID",
     "kind": "price",
     "priceKind": "Plan",
     "allowNone": false
    },
    "store_price": {
     "label": "Storage price (price book ID)",
     "unit": "ID",
     "kind": "price",
     "priceKind": "Unit",
     "allowNone": false
    },
    "read_price": {
     "label": "Read price (price book ID)",
     "unit": "ID",
     "kind": "price",
     "priceKind": "Unit",
     "allowNone": false
    },
    "min_saved": {
     "label": "Minutes saved per outcome",
     "unit": "minutes",
     "kind": "number"
    },
    "b_rate": {
     "label": "Loaded hourly rate of time saved",
     "unit": "USD per hour",
     "kind": "number"
    },
    "accept": {
     "label": "Quality or acceptance rate",
     "unit": "share",
     "kind": "percent"
    }
   },
   "archetypes": {
    "A1": {
     "code": "A1",
     "name": "Knowledge-worker assistant",
     "label": "A1 Knowledge-worker assistant",
     "preset": {
      "buy": "Seat",
      "seat_std": "SEAT_TEAM_STD",
      "seat_prem": "SEAT_TEAM_PREM",
      "prem_share": 0.1,
      "allow": 0,
      "top_share": 0.1,
      "top_mult": 5,
      "unit_price": "",
      "cap_cost": 0,
      "cap_outcomes": 0,
      "plateau": 0.6,
      "start": 1,
      "ramp": 6,
      "curve": "S",
      "basis": "per user",
      "o_user": 60,
      "direct": 0,
      "model": "M_SONNET5",
      "cheap": "M_HAIKU45",
      "route": 0.0,
      "tok_in": 2000,
      "tok_out": 500,
      "ctx": 0.0,
      "cached": 0.3,
      "cwrite": 0.05,
      "async_": 0.0,
      "resid": 1.0,
      "agentic": "No",
      "tool_calls": 0,
      "tool_price": "U_TOOL_SEARCH",
      "guard_units": 0,
      "guard_price": "U_GUARD_CF",
      "review": 0.05,
      "rev_rate": 46.89,
      "nsrc": 3,
      "ndocs": 20000,
      "pages": 5,
      "parse_price": "U_TEXTRACT_TXT",
      "emb_tok": 3000,
      "emb_price": "U_EMB_3L",
      "own_index": 1,
      "gb": 20,
      "read_units": 2,
      "plan_price": "PL_PINE_STD",
      "store_price": "U_PINE_STORE",
      "read_price": "U_PINE_READ",
      "min_saved": 2,
      "b_rate": 46.89,
      "accept": 0.9
     },
     "note": "Minutes saved: the worked example uses 2 per outcome (conservative) and, for a second team, 7 (calibrated to the low published self-reported figure, grade C*, evidence VAL-04).",
     "placeholder": false
    },
    "A2": {
     "code": "A2",
     "name": "Developer productivity and agents",
     "label": "A2 Developer productivity and agents",
     "preset": {
      "buy": "Seat + usage",
      "seat_std": "SEAT_ENT",
      "seat_prem": "SEAT_TEAM_PREM",
      "prem_share": 0.0,
      "allow": 0,
      "top_share": 0.1,
      "top_mult": 5,
      "unit_price": "",
      "cap_cost": 0,
      "cap_outcomes": 0,
      "plateau": 0.8,
      "start": 1,
      "ramp": 4,
      "curve": "Linear",
      "basis": "per user",
      "o_user": 400,
      "direct": 0,
      "model": "M_SONNET5",
      "cheap": "M_HAIKU45",
      "route": 0.0,
      "tok_in": 8000,
      "tok_out": 2000,
      "ctx": 0.1,
      "cached": 0.6,
      "cwrite": 0.05,
      "async_": 0.0,
      "resid": 1.0,
      "agentic": "Yes",
      "tool_calls": 0,
      "tool_price": "U_TOOL_SEARCH",
      "guard_units": 0,
      "guard_price": "U_GUARD_CF",
      "review": 0.2,
      "rev_rate": 46.89,
      "nsrc": 2,
      "ndocs": 50000,
      "pages": 3,
      "parse_price": "U_TEXTRACT_TXT",
      "emb_tok": 4000,
      "emb_price": "U_EMB_3L",
      "own_index": 1,
      "gb": 40,
      "read_units": 5,
      "plan_price": "PL_PINE_STD",
      "store_price": "U_PINE_STORE",
      "read_price": "U_PINE_READ",
      "min_saved": 4,
      "b_rate": 110.0,
      "accept": 0.85
     },
     "note": "",
     "placeholder": false
    },
    "A3": {
     "code": "A3",
     "name": "High-volume service operations",
     "label": "A3 High-volume service operations",
     "preset": {
      "buy": "Per-unit",
      "seat_std": "SEAT_TEAM_STD",
      "seat_prem": "SEAT_TEAM_PREM",
      "prem_share": 0.0,
      "allow": 0,
      "top_share": 0.1,
      "top_mult": 5,
      "unit_price": "OUT_FIN",
      "cap_cost": 0,
      "cap_outcomes": 0,
      "plateau": 0.85,
      "start": 2,
      "ramp": 6,
      "curve": "S",
      "basis": "direct volume",
      "o_user": 0,
      "direct": 40000,
      "model": "M_SONNET5",
      "cheap": "M_HAIKU45",
      "route": 0.0,
      "tok_in": 0,
      "tok_out": 0,
      "ctx": 0.0,
      "cached": 0.0,
      "cwrite": 0.0,
      "async_": 0.0,
      "resid": 1.0,
      "agentic": "No",
      "tool_calls": 0,
      "tool_price": "U_TOOL_SEARCH",
      "guard_units": 0,
      "guard_price": "U_GUARD_CF",
      "review": 0.1,
      "rev_rate": 46.89,
      "nsrc": 3,
      "ndocs": 8000,
      "pages": 4,
      "parse_price": "U_TEXTRACT_TXT",
      "emb_tok": 0,
      "emb_price": "U_EMB_3L",
      "own_index": 0,
      "gb": 0,
      "read_units": 0,
      "plan_price": "PL_PINE_STD",
      "store_price": "U_PINE_STORE",
      "read_price": "U_PINE_READ",
      "min_saved": 6,
      "b_rate": 46.89,
      "accept": 0.85
     },
     "note": "",
     "placeholder": false
    },
    "A4": {
     "code": "A4",
     "name": "Regulated document and decision work",
     "label": "A4 Regulated document and decision work",
     "preset": {
      "buy": "Per-unit",
      "seat_std": "SEAT_TEAM_STD",
      "seat_prem": "SEAT_TEAM_PREM",
      "prem_share": 0.0,
      "allow": 0,
      "top_share": 0.1,
      "top_mult": 5,
      "unit_price": "",
      "cap_cost": 0,
      "cap_outcomes": 0,
      "plateau": 0.7,
      "start": 3,
      "ramp": 5,
      "curve": "S",
      "basis": "per user",
      "o_user": 120,
      "direct": 0,
      "model": "M_OPUS5",
      "cheap": "M_SONNET5",
      "route": 0.5,
      "tok_in": 30000,
      "tok_out": 1500,
      "ctx": 0.0,
      "cached": 0.3,
      "cwrite": 0.05,
      "async_": 0.4,
      "resid": 1.1,
      "agentic": "No",
      "tool_calls": 0,
      "tool_price": "U_TOOL_SEARCH",
      "guard_units": 126,
      "guard_price": "U_GUARD_CF",
      "review": 1.0,
      "rev_rate": 46.89,
      "nsrc": 4,
      "ndocs": 200000,
      "pages": 8,
      "parse_price": "U_TEXTRACT_TBL",
      "emb_tok": 6000,
      "emb_price": "U_EMB_3L",
      "own_index": 1,
      "gb": 300,
      "read_units": 10,
      "plan_price": "PL_PINE_STD",
      "store_price": "U_PINE_STORE",
      "read_price": "U_PINE_READ",
      "min_saved": 8,
      "b_rate": 46.89,
      "accept": 0.95
     },
     "note": "",
     "placeholder": false
    },
    "A5": {
     "code": "A5",
     "name": "Embedded product feature",
     "label": "A5 Embedded product feature",
     "preset": {
      "buy": "Per-unit",
      "seat_std": "SEAT_TEAM_STD",
      "seat_prem": "SEAT_TEAM_PREM",
      "prem_share": 0.1,
      "allow": 0,
      "top_share": 0.1,
      "top_mult": 5,
      "unit_price": "",
      "cap_cost": 0,
      "cap_outcomes": 0,
      "plateau": 0.6,
      "start": 1,
      "ramp": 6,
      "curve": "S",
      "basis": "direct volume",
      "o_user": 0,
      "direct": 40000,
      "model": "M_SONNET5",
      "cheap": "M_HAIKU45",
      "route": 0.0,
      "tok_in": 2000,
      "tok_out": 500,
      "ctx": 0.0,
      "cached": 0.3,
      "cwrite": 0.05,
      "async_": 0.0,
      "resid": 1.0,
      "agentic": "No",
      "tool_calls": 0,
      "tool_price": "U_TOOL_SEARCH",
      "guard_units": 0,
      "guard_price": "U_GUARD_CF",
      "review": 0.02,
      "rev_rate": 46.89,
      "nsrc": 3,
      "ndocs": 20000,
      "pages": 5,
      "parse_price": "U_TEXTRACT_TXT",
      "emb_tok": 3000,
      "emb_price": "U_EMB_3L",
      "own_index": 1,
      "gb": 20,
      "read_units": 2,
      "plan_price": "PL_PINE_STD",
      "store_price": "U_PINE_STORE",
      "read_price": "U_PINE_READ",
      "min_saved": 2,
      "b_rate": 46.89,
      "accept": 0.9
     },
     "note": "No worked example yet: usage values are copied from A1 as placeholders. Replace them. This model values time saved, so revenue from an embedded feature is not captured.",
     "placeholder": true
    },
    "A6": {
     "code": "A6",
     "name": "Data and analytics assistant",
     "label": "A6 Data and analytics assistant",
     "preset": {
      "buy": "Seat",
      "seat_std": "SEAT_TEAM_STD",
      "seat_prem": "SEAT_TEAM_PREM",
      "prem_share": 0.1,
      "allow": 0,
      "top_share": 0.1,
      "top_mult": 5,
      "unit_price": "",
      "cap_cost": 0,
      "cap_outcomes": 0,
      "plateau": 0.6,
      "start": 1,
      "ramp": 6,
      "curve": "S",
      "basis": "per user",
      "o_user": 60,
      "direct": 0,
      "model": "M_SONNET5",
      "cheap": "M_HAIKU45",
      "route": 0.0,
      "tok_in": 2000,
      "tok_out": 500,
      "ctx": 0.0,
      "cached": 0.3,
      "cwrite": 0.05,
      "async_": 0.0,
      "resid": 1.0,
      "agentic": "No",
      "tool_calls": 0,
      "tool_price": "U_TOOL_SEARCH",
      "guard_units": 0,
      "guard_price": "U_GUARD_CF",
      "review": 0.25,
      "rev_rate": 46.89,
      "nsrc": 3,
      "ndocs": 20000,
      "pages": 5,
      "parse_price": "U_TEXTRACT_TXT",
      "emb_tok": 3000,
      "emb_price": "U_EMB_3L",
      "own_index": 1,
      "gb": 20,
      "read_units": 2,
      "plan_price": "PL_PINE_STD",
      "store_price": "U_PINE_STORE",
      "read_price": "U_PINE_READ",
      "min_saved": 2,
      "b_rate": 46.89,
      "accept": 0.9
     },
     "note": "No worked example yet: usage values are copied from A1 as placeholders. Replace them.",
     "placeholder": true
    }
   },
   "exampleTeams": [
    {
     "active": 1,
     "name": "Corporate knowledge assistant (conservative calibration)",
     "archetype": "A1 Knowledge-worker assistant",
     "bu": "Corporate functions",
     "buy": "Seat",
     "seat_std": "SEAT_TEAM_STD",
     "seat_prem": "SEAT_TEAM_PREM",
     "prem_share": 0.1,
     "allow": 0,
     "top_share": 0.1,
     "top_mult": 5,
     "unit_price": "",
     "cap_cost": 0,
     "cap_outcomes": 0,
     "licensed": 3000,
     "plateau": 0.6,
     "start": 1,
     "ramp": 6,
     "curve": "S",
     "basis": "per user",
     "o_user": 60,
     "direct": 0,
     "model": "M_SONNET5",
     "cheap": "M_HAIKU45",
     "route": 0.0,
     "tok_in": 2000,
     "tok_out": 500,
     "ctx": 0.0,
     "cached": 0.3,
     "cwrite": 0.05,
     "async_": 0.0,
     "resid": 1.0,
     "agentic": "No",
     "tool_calls": 0,
     "tool_price": "U_TOOL_SEARCH",
     "guard_units": 0,
     "guard_price": "U_GUARD_CF",
     "review": 0.05,
     "rev_rate": 46.89,
     "nsrc": 3,
     "ndocs": 20000,
     "pages": 5,
     "parse_price": "U_TEXTRACT_TXT",
     "emb_tok": 3000,
     "emb_price": "U_EMB_3L",
     "own_index": 1,
     "gb": 20,
     "read_units": 2,
     "plan_price": "PL_PINE_STD",
     "store_price": "U_PINE_STORE",
     "read_price": "U_PINE_READ",
     "min_saved": 2,
     "b_rate": 46.89,
     "accept": 0.9
    },
    {
     "active": 1,
     "name": "Engineering assistant",
     "archetype": "A2 Developer productivity and agents",
     "bu": "Engineering",
     "buy": "Seat + usage",
     "seat_std": "SEAT_ENT",
     "seat_prem": "SEAT_TEAM_PREM",
     "prem_share": 0.0,
     "allow": 0,
     "top_share": 0.1,
     "top_mult": 5,
     "unit_price": "",
     "cap_cost": 0,
     "cap_outcomes": 0,
     "licensed": 400,
     "plateau": 0.8,
     "start": 1,
     "ramp": 4,
     "curve": "Linear",
     "basis": "per user",
     "o_user": 400,
     "direct": 0,
     "model": "M_SONNET5",
     "cheap": "M_HAIKU45",
     "route": 0.0,
     "tok_in": 8000,
     "tok_out": 2000,
     "ctx": 0.1,
     "cached": 0.6,
     "cwrite": 0.05,
     "async_": 0.0,
     "resid": 1.0,
     "agentic": "Yes",
     "tool_calls": 0,
     "tool_price": "U_TOOL_SEARCH",
     "guard_units": 0,
     "guard_price": "U_GUARD_CF",
     "review": 0.2,
     "rev_rate": 46.89,
     "nsrc": 2,
     "ndocs": 50000,
     "pages": 3,
     "parse_price": "U_TEXTRACT_TXT",
     "emb_tok": 4000,
     "emb_price": "U_EMB_3L",
     "own_index": 1,
     "gb": 40,
     "read_units": 5,
     "plan_price": "PL_PINE_STD",
     "store_price": "U_PINE_STORE",
     "read_price": "U_PINE_READ",
     "min_saved": 4,
     "b_rate": 110.0,
     "accept": 0.85
    },
    {
     "active": 1,
     "name": "Customer service agent",
     "archetype": "A3 High-volume service operations",
     "bu": "Customer operations",
     "buy": "Per-unit",
     "seat_std": "SEAT_TEAM_STD",
     "seat_prem": "SEAT_TEAM_PREM",
     "prem_share": 0.0,
     "allow": 0,
     "top_share": 0.1,
     "top_mult": 5,
     "unit_price": "OUT_FIN",
     "cap_cost": 0,
     "cap_outcomes": 0,
     "licensed": 60,
     "plateau": 0.85,
     "start": 2,
     "ramp": 6,
     "curve": "S",
     "basis": "direct volume",
     "o_user": 0,
     "direct": 40000,
     "model": "M_SONNET5",
     "cheap": "M_HAIKU45",
     "route": 0.0,
     "tok_in": 0,
     "tok_out": 0,
     "ctx": 0.0,
     "cached": 0.0,
     "cwrite": 0.0,
     "async_": 0.0,
     "resid": 1.0,
     "agentic": "No",
     "tool_calls": 0,
     "tool_price": "U_TOOL_SEARCH",
     "guard_units": 0,
     "guard_price": "U_GUARD_CF",
     "review": 0.1,
     "rev_rate": 46.89,
     "nsrc": 3,
     "ndocs": 8000,
     "pages": 4,
     "parse_price": "U_TEXTRACT_TXT",
     "emb_tok": 0,
     "emb_price": "U_EMB_3L",
     "own_index": 0,
     "gb": 0,
     "read_units": 0,
     "plan_price": "PL_PINE_STD",
     "store_price": "U_PINE_STORE",
     "read_price": "U_PINE_READ",
     "min_saved": 6,
     "b_rate": 46.89,
     "accept": 0.85
    },
    {
     "active": 1,
     "name": "Regulated document review",
     "archetype": "A4 Regulated document and decision work",
     "bu": "Risk and legal",
     "buy": "Per-unit",
     "seat_std": "SEAT_TEAM_STD",
     "seat_prem": "SEAT_TEAM_PREM",
     "prem_share": 0.0,
     "allow": 0,
     "top_share": 0.1,
     "top_mult": 5,
     "unit_price": "",
     "cap_cost": 0,
     "cap_outcomes": 0,
     "licensed": 150,
     "plateau": 0.7,
     "start": 3,
     "ramp": 5,
     "curve": "S",
     "basis": "per user",
     "o_user": 120,
     "direct": 0,
     "model": "M_OPUS5",
     "cheap": "M_SONNET5",
     "route": 0.5,
     "tok_in": 30000,
     "tok_out": 1500,
     "ctx": 0.0,
     "cached": 0.3,
     "cwrite": 0.05,
     "async_": 0.4,
     "resid": 1.1,
     "agentic": "No",
     "tool_calls": 0,
     "tool_price": "U_TOOL_SEARCH",
     "guard_units": 126,
     "guard_price": "U_GUARD_CF",
     "review": 1.0,
     "rev_rate": 46.89,
     "nsrc": 4,
     "ndocs": 200000,
     "pages": 8,
     "parse_price": "U_TEXTRACT_TBL",
     "emb_tok": 6000,
     "emb_price": "U_EMB_3L",
     "own_index": 1,
     "gb": 300,
     "read_units": 10,
     "plan_price": "PL_PINE_STD",
     "store_price": "U_PINE_STORE",
     "read_price": "U_PINE_READ",
     "min_saved": 8,
     "b_rate": 46.89,
     "accept": 0.95
    },
    {
     "active": 1,
     "name": "Sales assistant (published-range calibration)",
     "archetype": "A1 Knowledge-worker assistant",
     "bu": "Sales and marketing",
     "buy": "Seat",
     "seat_std": "SEAT_TEAM_STD",
     "seat_prem": "SEAT_TEAM_PREM",
     "prem_share": 0.1,
     "allow": 0,
     "top_share": 0.1,
     "top_mult": 5,
     "unit_price": "",
     "cap_cost": 0,
     "cap_outcomes": 0,
     "licensed": 2000,
     "plateau": 0.6,
     "start": 1,
     "ramp": 6,
     "curve": "S",
     "basis": "per user",
     "o_user": 60,
     "direct": 0,
     "model": "M_SONNET5",
     "cheap": "M_HAIKU45",
     "route": 0.0,
     "tok_in": 2000,
     "tok_out": 500,
     "ctx": 0.0,
     "cached": 0.3,
     "cwrite": 0.05,
     "async_": 0.0,
     "resid": 1.0,
     "agentic": "No",
     "tool_calls": 0,
     "tool_price": "U_TOOL_SEARCH",
     "guard_units": 0,
     "guard_price": "U_GUARD_CF",
     "review": 0.05,
     "rev_rate": 46.89,
     "nsrc": 2,
     "ndocs": 10000,
     "pages": 5,
     "parse_price": "U_TEXTRACT_TXT",
     "emb_tok": 3000,
     "emb_price": "U_EMB_3L",
     "own_index": 1,
     "gb": 10,
     "read_units": 2,
     "plan_price": "PL_PINE_STD",
     "store_price": "U_PINE_STORE",
     "read_price": "U_PINE_READ",
     "min_saved": 7,
     "b_rate": 46.89,
     "accept": 0.9
    }
   ],
   "template": {
    "orgFields": [
     "name",
     "shape",
     "alloc",
     "horizon",
     "pd_rate",
     "hours_day",
     "work_days",
     "obs_per_out"
    ],
    "enterpriseFields": [
     "env_month",
     "comp_year",
     "lic_year"
    ],
    "requiredTeamFields": [
     "archetype",
     "buy",
     "licensed",
     "plateau",
     "basis",
     "min_saved"
    ],
    "teamFieldOrder": [
     "name",
     "active",
     "archetype",
     "bu",
     "buy",
     "seat_std",
     "seat_prem",
     "prem_share",
     "allow",
     "top_share",
     "top_mult",
     "unit_price",
     "cap_cost",
     "licensed",
     "plateau",
     "start",
     "ramp",
     "curve",
     "basis",
     "o_user",
     "direct",
     "model",
     "cheap",
     "route",
     "tok_in",
     "tok_out",
     "ctx",
     "cached",
     "cwrite",
     "async_",
     "resid",
     "agentic",
     "tool_calls",
     "tool_price",
     "guard_units",
     "guard_price",
     "review",
     "rev_rate",
     "nsrc",
     "ndocs",
     "pages",
     "parse_price",
     "emb_tok",
     "emb_price",
     "own_index",
     "gb",
     "read_units",
     "plan_price",
     "store_price",
     "read_price",
     "min_saved",
     "b_rate",
     "accept"
    ]
   }
  };
  if (typeof module === "object" && module.exports) module.exports = DATA;
  else root.DATA = DATA;
}(typeof self !== "undefined" ? self : this));
